# Generated by Django 2.2.3 on 2022-03-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0014_move_short_descriptions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ("facility", "-priority", "name"),
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
            },
        ),
        migrations.AlterModelOptions(
            name="workplace",
            options={
                "ordering": ("facility", "-priority", "name"),
                "verbose_name": "workplace",
                "verbose_name_plural": "workplaces",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="priority"),
        ),
        migrations.AddField(
            model_name="workplace",
            name="priority",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="priority"),
        ),
    ]
