# Generated by Django 4.0.3 on 2022-03-29 08:01

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0017_make_memberships_unique"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": (
                    "facility",
                    django.db.models.expressions.OrderBy(
                        django.db.models.expressions.F("priority"),
                        descending=True,
                        nulls_last=True,
                    ),
                    "name",
                ),
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
            },
        ),
        migrations.AlterModelOptions(
            name="workplace",
            options={
                "ordering": (
                    "facility",
                    django.db.models.expressions.OrderBy(
                        django.db.models.expressions.F("priority"),
                        descending=True,
                        nulls_last=True,
                    ),
                    "name",
                ),
                "verbose_name": "workplace",
                "verbose_name_plural": "workplaces",
            },
        ),
    ]
