# Generated by Django 4.0.4 on 2022-04-13 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0018_alter_ordering_by_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskAttribute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=32, verbose_name="attribute name"),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="short description"
                    ),
                ),
                (
                    "value_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "checkbox"), (2, "text")],
                        default=2,
                        verbose_name="value type",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        choices=[(1, "checkbox"), (2, "text")],
                        default=False,
                        verbose_name="is required",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="organizations.task",
                        verbose_name="attribute",
                    ),
                ),
            ],
            options={
                "verbose_name": "attribute",
                "verbose_name_plural": "shift notifications",
            },
        ),
    ]
