# Generated by Django 4.0.4 on 2022-04-13 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0019_add_taskattribute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskattribute",
            name="is_required",
            field=models.BooleanField(default=False, verbose_name="is required"),
        ),
        migrations.AlterField(
            model_name="taskattribute",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="organizations.task",
                verbose_name="task attribute",
            ),
        ),
    ]
