# Generated by Django 2.0.5 on 2019-07-18 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0037_slots_positive_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='facility',
            field=models.ForeignKey(verbose_name='facility', to='organizations.Facility',
                                    on_delete=django.db.models.deletion.PROTECT),
        ),
        migrations.AlterField(
            model_name='shift',
            name='task',
            field=models.ForeignKey(verbose_name='task', to='organizations.Task',
                                    on_delete=django.db.models.deletion.PROTECT),
        ),
        migrations.AlterField(
            model_name='shift',
            name='workplace',
            field=models.ForeignKey(verbose_name='workplace', to='organizations.Workplace',
                                    null=True, blank=True,
                                    on_delete=django.db.models.deletion.PROTECT),
        ),
    ]
