# Generated by Django 4.0.3 on 2022-04-01 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("scheduler", "0040_min_shift_slots"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftMessageToHelpers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "send_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="send date"),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        to="accounts.useraccount", verbose_name="recipients"
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="msg_sender",
                        to="accounts.useraccount",
                        verbose_name="sender",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="scheduler.shift",
                        verbose_name="Shift",
                    ),
                ),
            ],
            options={
                "verbose_name": "shift notification",
                "verbose_name_plural": "shift notifications",
            },
        ),
    ]
