# Generated by Django 4.0.3 on 2022-03-29 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0041_shiftmessagetohelpers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftmessagetohelpers',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 13, 35, 44, 361728, tzinfo=utc)),
        ),
    ]
