# Generated by Django 4.0.3 on 2022-04-12 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0041_add_shift_messages"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftmessagetohelpers",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="scheduler.shift",
                verbose_name="Shift",
            ),
        ),
        migrations.AlterField(
            model_name="shiftmessagetohelpers",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="msg_sender",
                to="accounts.useraccount",
                verbose_name="sender",
            ),
        ),
    ]
