# Generated by Django 4.0.3 on 2022-03-29 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0042_alter_shiftmessagetohelpers_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftmessagetohelpers',
            name='send_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
